CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(80) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

DROP TABLE T_OFFICES;

# COMENTARIO

CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(90) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

ALTER TABLE T_OFFICES DROP COLUMN OFFC_NAME;

ALTER TABLE T_OFFICES ADD COLUMN OFFC_CITY VARCHAR(50) NOT NULL AFTER OFFC_COUNTRY;

#FORMA DIRECTA (DE ESTA FORMA NO SE PUEDE CAMBIAR EL NOMBRE DE LA COLUMNA)
#ALTER TABLE T_OFFICES MODIFY COLUMN OFFC_DESCRIPTION VARCHAR(100);
#FORMA COMPLETA
ALTER TABLE T_OFFICES CHANGE COLUMN OFFC_DESCRIPTION OFFC_DESCRIPTION VARCHAR(100) NOT NULL;

#DESC T_OFFICES;

/*INSERT INTO T_OFFICES (
	OFFC_ID,OFFC_COUNTRY,OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
20,'Chile','Santiago','Oficina principal de Chile'
),
(
30,'Argentina','Buenos Aires', NULL
);*/

INSERT INTO T_OFFICES (  
	OFFC_ID, OFFC_COUNTRY, OFFC_CITY 
) 
VALUES 
(  
	11, 'España', 'Barcelona' 
),
(  
	12, 'España', 'Valladolid' 
);

UPDATE T_OFFICES SET 
	OFFC_CITY = 'Valladolid',  
    OFFC_DESCRIPTION = 'Colabora en j-everis' 
WHERE OFFC_ID = 12;

DELETE FROM T_OFFICES WHERE OFFC_ID = 30;

insert into T_OFFICES (OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION)
values
(20,'Chile','Santiago','Oficina principal de Chile'),
(30,'Argentina','Buenos aires',null);

UPDATE T_OFFICES SET 
    OFFC_CITY = 'Buenos Aires' 
WHERE OFFC_ID = 30;

CREATE TABLE T_KNOWLEDGE_LINES 
(
	KNLN_ID INT(11) NOT NULL, 
	KNLN_NAME VARCHAR(45) NOT NULL,  
    PRIMARY KEY (KNLN_ID) 
);
INSERT INTO T_KNOWLEDGE_LINES (`KNLN_ID`, `KNLN_NAME`) 
	VALUES 
    (10, 'Java'),
    (20, '.NET'),
    (30, 'Mainframe');
    
#DESC T_KNOWLEDGE_LINES;

ALTER TABLE T_OFFICES ADD PRIMARY KEY (OFFC_ID);

CREATE TABLE T_EMPLOYEES (
	EMPL_ID INT NOT NULL AUTO_INCREMENT,
    OFFC_ID INT NOT NULL,
    KNLN_ID INT,
    EMPL_FORNAME VARCHAR(50) NOT NULL,
    EMPL_MIDDLE_NAME VARCHAR(50),
    EMPL_SURNAME VARCHAR(50) NOT NULL,
    EMPL_NUMBER INT NOT NULL,
    EMPL_HIRE_DATE DATETIME NOT NULL,
    EMPL_MENTOR_ID INT,
    PRIMARY KEY (EMPL_ID)
); 

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 10,
 10,
 'Juan',
 'Pérez',
 150,
 '2005-04-15'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 20,
 'Antonio',
 'Gómez',
 250,
 '2005-06-05'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_MIDDLE_NAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 20,
 'Juan',
 'Emilio',
 'Parlón',
 210,
 '2005-01-01'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE,
EMPL_MENTOR_ID)
VALUES
(
 11,
 20,
 'Luis',
 'González',
 160,
 '2006-05-18',
 1
);

INSERT INTO t_employees
(OFFC_ID,
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 'Pedro',
 'García',
 180,
 '2005-05-18'
);

CREATE TABLE T_PROJECTS (
  PRJT_ID INT NOT NULL  AUTO_INCREMENT,
  PRJT_CODE VARCHAR(16) NOT NULL,
  PRJT_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY (PRJT_ID)
);

CREATE TABLE T_PROJECTS_EMPLOYEES (
  PRJT_ID INT NOT NULL,
  EMPL_ID INT NOT NULL,
  PRIMARY KEY (PRJT_ID,EMPL_ID)
); 

INSERT INTO t_projects(
PRJT_CODE,
PRJT_NAME
)
VALUES
(
 'EXT-001000-01234',
 'Gestión de usuarios'
),
(
 'INT-001000-03200',
 'Cursos de formación'
);

INSERT INTO T_PROJECTS_EMPLOYEES(
PRJT_ID,
EMPL_ID
)
VALUES
(
 1,
 1
),
(
 2,
 1
),
(
1,
4
);

#FOREIGN KEY DE OFICINAS Y KNWOLEDGES EN EMPLOYEES
ALTER TABLE T_EMPLOYEES
	ADD INDEX FK_EMPL_OFFC (OFFC_ID),
    ADD CONSTRAINT FK_EMPL_OFFC
    FOREIGN KEY (OFFC_ID)
    REFERENCES T_OFFICES (OFFC_ID);
    
ALTER TABLE T_EMPLOYEES     
	ADD INDEX FK_EMPL_KNLN (KNLN_ID),
    ADD CONSTRAINT FK_EMPL_KNLN
    FOREIGN KEY (KNLN_ID)
    REFERENCES T_KNOWLEDGE_LINES (KNLN_ID);    

#AUTOREFERENCIADA (NO HEMOS HECHO CONSTRAINT NOT NULL EN EL CAMPOS EMPL_MENTOR_ID)
ALTER TABLE T_EMPLOYEES    
	ADD INDEX FK_EMPL_MENTOR_ID (EMPL_MENTOR_ID),
    ADD CONSTRAINT FK_EMPL_MENTOR_ID
    FOREIGN KEY (EMPL_MENTOR_ID)
    REFERENCES T_EMPLOYEES (EMPL_ID);    
    
#TABLA INTERMEDIA
ALTER TABLE T_PROJECTS_EMPLOYEES
	ADD INDEX FK_PREM_PRJT (PRJT_ID),
    ADD CONSTRAINT FK_PREM_PRJT
    FOREIGN KEY (PRJT_ID)
    REFERENCES T_PROJECTS (PRJT_ID);

ALTER TABLE T_PROJECTS_EMPLOYEES
	ADD INDEX FK_PREM_EMPL (EMPL_ID),
    ADD CONSTRAINT FK_PREM_EMPL
    FOREIGN KEY (EMPL_ID)
    REFERENCES T_EMPLOYEES (EMPL_ID);


SELECT em.EMPL_FORNAME, em.EMPL_SURNAME, of.OFFC_CITY,of.OFFC_COUNTRY, kn.KNLN_NAME, em.EMPL_MENTOR_ID 
FROM t_employees em 
INNER JOIN T_OFFICES of ON em.OFFC_ID=of.OFFC_ID 
left outer JOIN t_knowledge_lines kn ON em.KNLN_ID=kn.KNLN_ID 
where of.OFFC_COUNTRY IN ('España','Chile') 
and em.EMPL_MENTOR_ID is null;

#EN ESTA SELECT HE PUESTO LA TABLA INTERMEDIA AL PRINCIPIO, A DIFERENCIA DE LA DE LA VISTA, NO VARIA
#LOS RESULTADOS
SELECT PRO.PRJT_CODE,PRO.PRJT_NAME, EM.EMPL_NUMBER,EM.EMPL_FORNAME,EM.EMPL_SURNAME FROM t_projects_employees PREM INNER JOIN T_PROJECTS PRO ON PRO.PRJT_ID=PREM.PRJT_ID INNER JOIN t_employees EM ON PREM.EMPL_ID=EM.EMPL_ID;

#LOS NOMBRE DE LOS CAMPOS DE LA VISTA SE PUEDEN CAMBIAR (SON COMO UN AS)
CREATE VIEW V_PROJECTS_EMPLOYEES 
(PRJT_CODE, PRJT_NAME, EMPL_NUMBER, EMPL_FORNAME, EMPL_SURNAME) AS
SELECT PRO.PRJT_CODE,PRO.PRJT_NAME, EM.EMPL_NUMBER,EM.EMPL_FORNAME,EM.EMPL_SURNAME 
FROM T_PROJECTS PRO 
INNER JOIN t_projects_employees PREM ON PRO.PRJT_ID=PREM.PRJT_ID 
INNER JOIN t_employees EM ON PREM.EMPL_ID=EM.EMPL_ID;

SELECT * FROM db_empl.v_projects_employees WHERE PRJT_CODE LIKE 'EXT%';

CREATE TABLE T_DOCUMENTS (
	DOCS_ID INT NOT NULL AUTO_INCREMENT,
    EMPL_ID INT NOT NULL,  
    DOCS_NAME VARCHAR(100) NOT NULL,  
    DOCS_TYPE VARCHAR(50) NOT NULL,  
    PRIMARY KEY (`DOCS_ID`)
);

ALTER TABLE T_DOCUMENTS
	ADD INDEX FK_DOCS_EMPL (EMPL_ID),
	ADD CONSTRAINT FK_DOCS_EMPL
    FOREIGN KEY (EMPL_ID)
    REFERENCES T_EMPLOYEES (EMPL_ID);
    
ALTER TABLE T_DOCUMENTS 
	ADD CONSTRAINT CT_CK_DOCS_TYPE  
    CHECK (DOCS_TYPE IN ('PDF','XLS','DOC','PPT'));
    
ALTER TABLE T_DOCUMENTS MODIFY COLUMN DOCS_TYPE ENUM('PDF','XLS','DOC','PPT');

INSERT INTO T_DOCUMENTS (EMPL_ID, DOCS_NAME, DOCS_TYPE) 
VALUES 
(1, 'Titulo', 'PDF'), 
(1, 'Curriculum', 'DOC'), 
(1, 'Certificado OCP', 'PDF'), 
(1, 'Matriz conocimientos', 'XLS'), 
(2, 'Grado', 'PDF'), 
(2, 'Curriculum', 'DOC'), 
(2, 'Certificado MS', 'PDF'), 
(3, 'Titulo', 'PDF');    

SELECT CONCAT(EMPL_FORNAME, ' ', EMPL_SURNAME) AS FULL_NAME, 
COUNT(d.DOCS_ID) AS NUM_DOCS FROM T_EMPLOYEES e
LEFT OUTER JOIN T_DOCUMENTS d ON e.EMPL_ID=d.EMPL_ID
GROUP BY e.EMPL_ID
order by num_docs
LIMIT 1,2;