CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(80) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

DROP TABLE T_OFFICES;

# COMENTARIO

CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(90) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

ALTER TABLE T_OFFICES DROP COLUMN OFFC_NAME;

ALTER TABLE T_OFFICES ADD COLUMN OFFC_CITY VARCHAR(50) NOT NULL AFTER OFFC_COUNTRY;

#FORMA DIRECTA (DE ESTA FORMA NO SE PUEDE CAMBIAR EL NOMBRE DE LA COLUMNA)
#ALTER TABLE T_OFFICES MODIFY COLUMN OFFC_DESCRIPTION VARCHAR(100);
#FORMA COMPLETA
ALTER TABLE T_OFFICES CHANGE COLUMN OFFC_DESCRIPTION OFFC_DESCRIPTION VARCHAR(100) NOT NULL;

#DESC T_OFFICES;

/*INSERT INTO T_OFFICES (
	OFFC_ID,OFFC_COUNTRY,OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
20,'Chile','Santiago','Oficina principal de Chile'
),
(
30,'Argentina','Buenos Aires', NULL
);*/

INSERT INTO T_OFFICES (  
	OFFC_ID, OFFC_COUNTRY, OFFC_CITY 
) 
VALUES 
(  
	11, 'España', 'Barcelona' 
),
(  
	12, 'España', 'Valladolid' 
);

UPDATE T_OFFICES SET 
	OFFC_CITY = 'Valladolid',  
    OFFC_DESCRIPTION = 'Colabora en j-everis' 
WHERE OFFC_ID = 12;

DELETE FROM T_OFFICES WHERE OFFC_ID = 30;

insert into T_OFFICES (OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION)
values
(20,'Chile','Santiago','Oficina principal de Chile'),
(30,'Argentina','Buenos aires',null);

UPDATE T_OFFICES SET 
    OFFC_CITY = 'Buenos Aires' 
WHERE OFFC_ID = 30;

CREATE TABLE T_KNOWLEDGE_LINES 
(
	KNLN_ID INT(11) NOT NULL, 
	KNLN_NAME VARCHAR(45) NOT NULL,  
    PRIMARY KEY (KNLN_ID) 
);
INSERT INTO T_KNOWLEDGE_LINES (`KNLN_ID`, `KNLN_NAME`) 
	VALUES 
    (10, 'Java'),
    (20, '.NET'),
    (30, 'Mainframe');
    
#DESC T_KNOWLEDGE_LINES;

ALTER TABLE T_OFFICES ADD PRIMARY KEY (OFFC_ID);

CREATE TABLE T_EMPLOYEES (
	EMPL_ID INT NOT NULL AUTO_INCREMENT,
    OFFC_ID INT NOT NULL,
    KNLN_ID INT,
    EMPL_FORNAME VARCHAR(50) NOT NULL,
    EMPL_MIDDLE_NAME VARCHAR(50),
    EMPL_SURNAME VARCHAR(50) NOT NULL,
    EMPL_NUMBER INT NOT NULL,
    EMPL_HIRE_DATE DATETIME NOT NULL,
    EMPL_MENTOR_ID INT,
    PRIMARY KEY (EMPL_ID)
); 

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 10,
 10,
 'Juan',
 'Pérez',
 150,
 '2005-04-15'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 20,
 'Antonio',
 'Gómez',
 250,
 '2005-06-05'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_MIDDLE_NAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 20,
 'Juan',
 'Emilio',
 'Parlón',
 210,
 '2005-01-01'
);

INSERT INTO t_employees
(OFFC_ID,
KNLN_ID, 
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE,
EMPL_MENTOR_ID)
VALUES
(
 11,
 20,
 'Luis',
 'González',
 160,
 '2006-05-18',
 1
);

INSERT INTO t_employees
(OFFC_ID,
EMPL_FORNAME,
EMPL_SURNAME,
EMPL_NUMBER,
EMPL_HIRE_DATE)
VALUES
(
 20,
 'Pedro',
 'García',
 180,
 '2005-05-18'
);
