CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(80) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

DROP TABLE T_OFFICES;

# COMENTARIO

CREATE TABLE T_OFFICES (
	OFFC_ID INT NOT NULL, 
    OFFC_COUNTRY VARCHAR(30) NOT NULL, 
    OFFC_DESCRIPTION VARCHAR(90) NOT NULL, 
    OFFC_NAME VARCHAR(30)
);

ALTER TABLE T_OFFICES DROP COLUMN OFFC_NAME;

ALTER TABLE T_OFFICES ADD COLUMN OFFC_CITY VARCHAR(50) NOT NULL AFTER OFFC_COUNTRY;

#FORMA DIRECTA (DE ESTA FORMA NO SE PUEDE CAMBIAR EL NOMBRE DE LA COLUMNA)
ALTER TABLE T_OFFICES MODIFY COLUMN OFFC_DESCRIPTION VARCHAR(100);
#FORMA COMPLETA
ALTER TABLE T_OFFICES CHANGE COLUMN OFFC_DESCRIPTION OFFC_DESCRIPTION VARCHAR(100) NOT NULL;

#DESC T_OFFICES;

INSERT INTO T_OFFICES (
	OFFC_ID,OFFC_COUNTRY,OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
20,'Chile','Santiago','Principal de Chile'
),
(
30,'Argentina','Buenos Aires', NULL
);