CREATE DATABASE DB_MECANICO;

USE DB_MECANICO;

CREATE TABLE T_PROVEEDORES(
	PROV_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_NOM VARCHAR(50) NOT NULL,
	PRIMARY KEY (PROV_ID)
);

CREATE TABLE T_PIEZAS(
	PIEZ_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PIEZ_NOM VARCHAR(100) NOT NULL,

	PRIMARY KEY (PIEZ_ID)
);

CREATE TABLE T_PRECIOS(
	PREC_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_ID INT UNSIGNED NOT NULL,
	PIEZ_ID INT UNSIGNED NOT NULL,
    PRECIO NUMERIC (10,2),
	PRIMARY KEY (PREC_ID)
);

ALTER TABLE T_PRECIOS
	ADD INDEX FK_PREC_PROV (PROV_ID),
    ADD CONSTRAINT FK_PREC_PROV
    FOREIGN KEY (PROV_ID)
    REFERENCES T_PROVEEDORES (PROV_ID);

ALTER TABLE T_PRECIOS
	ADD INDEX FK_PREC_PIEZ (PIEZ_ID),
    ADD CONSTRAINT FK_PREC_PIEZ
    FOREIGN KEY (PIEZ_ID)
    REFERENCES T_PIEZAS (PIEZ_ID);
    

#ALTER TABLE T_PRECIOS ADD COLUMN PRECIO NUMERIC(10,2);

ALTER TABLE T_PRECIOS ADD UNIQUE (PROV_ID,PIEZ_ID);    

ALTER TABLE `db_mecanico`.`t_precios` 
DROP FOREIGN KEY `FK_PREC_PIEZ`;
ALTER TABLE `db_mecanico`.`t_precios` 
ADD CONSTRAINT `FK_PREC_PIEZ`
  FOREIGN KEY (`PIEZ_ID`)
  REFERENCES `db_mecanico`.`t_piezas` (`PIEZ_ID`)
  ON UPDATE CASCADE;

ALTER TABLE `db_mecanico`.`t_precios` 
DROP FOREIGN KEY `FK_PREC_PROV`;
ALTER TABLE `db_mecanico`.`t_precios` 
ADD CONSTRAINT `FK_PREC_PROV`
  FOREIGN KEY (`PROV_ID`)
  REFERENCES `db_mecanico`.`t_proveedores` (`PROV_ID`)
  ON UPDATE CASCADE;


INSERT INTO T_PIEZAS (PIEZ_NOM) VALUES
('Carburador Opel Corsa'),
('Volante Nissan Qashqai'),
('Tubo de escape Mazda 6'),
('Motor Reanult Megane'),
('Asiento conductor Citröen Picasso C4'),
('Centralita Peugeot 306 ;-)'),
('Palanca intermitente SEAT León');

INSERT INTO T_PROVEEDORES (PROV_NOM) VALUES
('Valeo'),
('Bosch'),
('Delphi'),
('Lausan'),
('Staedler'),
('Motorok');

INSERT INTO T_PRECIOS (PIEZ_ID,PROV_ID,PRECIO) VALUES
(1,1,250.45),
(2,1,120.33),
(3,2,80.99),
(4,2,810.99),
(5,3,110.23),
(6,4,500),
(7,5,25.76);

INSERT INTO T_PRECIOS (PIEZ_ID,PROV_ID,PRECIO) VALUES (7,5,25.76);


SELECT pz.PIEZ_NOM,pro.PROV_NOM,pr.PRECIO FROM db_mecanico.t_precios pr INNER JOIN T_PIEZAS pz ON pr.PIEZ_ID=pz.PIEZ_ID INNER JOIN T_PROVEEDORES pro ON pr.PROV_ID=pro.PROV_ID;

select count(pi.PIEZ_ID),piez_nom,round(avg(precio),2) from t_precios pr inner join t_piezas pi on pr.piez_id=pi.piez_id group by pr.piez_id order by pi.PIEZ_NOM;

select pro.prov_nom, round(avg(pr.precio),2) as precio_medio_prov from t_precios pr inner join t_proveedores pro on pr.prov_id=pro.prov_id group by pr.prov_id order by pro.PROV_NOM;

SELECT DISTINCT pz.PIEZ_NOM, pro.PROV_NOM FROM t_precios pr INNER JOIN T_PIEZAS pz ON pr.PIEZ_ID=pz.PIEZ_ID INNER JOIN T_PROVEEDORES pro ON pr.PROV_ID=pro.PROV_ID WHERE pz.PIEZ_ID IN(1,2);

SELECT PROV_NOM FROM t_PROVEEDORES pr WHERE PROV_ID IN(SELECT PROV_ID FROM T_PRECIOS WHERE PIEZ_ID=1);

SELECT pz.PIEZ_NOM, pro.PROV_NOM FROM t_precios pr INNER JOIN T_PIEZAS pz ON pr.PIEZ_ID=pz.PIEZ_ID INNER JOIN T_PROVEEDORES pro ON pr.PROV_ID=pro.PROV_ID WHERE pro.PROV_NOM='Valeo';

SELECT PIEZ_ID, MAX(PRECIO) FROM t_precios GROUP BY PIEZ_ID;

SELECT pz.PIEZ_ID,pz.PIEZ_NOM, pro.PROV_NOM, pr.PRECIO FROM t_precios pr INNER JOIN T_PIEZAS pz ON pr.PIEZ_ID=pz.PIEZ_ID INNER JOIN T_PROVEEDORES pro ON pr.PROV_ID=pro.PROV_ID WHERE CONCAT(PR.PIEZ_ID,'',PR.PRECIO) IN(SELECT CONCAT(PIEZ_ID,'',MAX(PRECIO)) FROM t_precios GROUP BY PIEZ_ID);

SELECT CONCAT(PIEZ_ID,'',MAX(PRECIO)) FROM T_PRECIOS GROUP BY PIEZ_ID;

SELECT PIEZ_ID, MAX(PRECIO) FROM T_PRECIOS GROUP BY PIEZ_ID;

UPDATE T_PRECIOS SET PRECIO = PRECIO+1;

DELETE FROM T_PRECIOS WHERE PROV_ID=1 AND PIEZ_ID=1